// This file was autogenerated by /Users/nr52/projectX/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../xtk/core/base.js', ['X.base'], ['X']);
goog.addDependency('../../../xtk/core/exception.js', ['X.exception'], ['X.base']);
goog.addDependency('../../../xtk/visualization/renderer.js', ['X.renderer'], ['X.base', 'X.exception', 'goog.dom']);
goog.addDependency('../../../xtk/visualization/renderer2D.js', ['X.renderer2D'], ['X.renderer']);
goog.addDependency('../../../xtk/visualization/renderer3D.js', ['X.renderer3D'], ['X.renderer']);
goog.addDependency('../../../xtk/xtk.js', ['X'], []);
