// This file was autogenerated by /Users/nr52/projectX/xtk/lib/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../../base.js', ['X.base'], ['X']);
goog.addDependency('../../../../../../console.js', ['X.console'], ['X.base', 'X.exception', 'goog.dom']);
goog.addDependency('../../../../../../exception.js', ['X.exception'], ['X.base']);
goog.addDependency('../../../../../../renderer.js', ['X.renderer'], ['X.base', 'X.exception', 'goog.dom']);
goog.addDependency('../../../../../../renderer2D.js', ['X.renderer2D'], ['X.renderer']);
goog.addDependency('../../../../../../renderer3D.js', ['X.renderer3D'], ['X.renderer']);
