// This file was autogenerated by /Users/nr52/projectX/xtk/lib/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../../../sampleApp/sampleApp.js', ['sampleApp', 'sampleApp.run'], ['X.console', 'X.renderer2D', 'X.renderer3D']);
