// This file was autogenerated by /Users/d/Projects/X/xtk/lib/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../sampleApp/js/sampleApp.js', ['sampleApp', 'sampleApp.run'], ['X.box', 'X.object', 'X.renderer3D', 'X.triplets']);
